name: Test CfPWeb
permissions:
  contents: read

on:
  push:
    paths:
      - "CfPWeb/**"
      - ".github/workflows/test-cfpweb.yml"

jobs:
  build:
    name: Build CfPWeb
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Swift
        uses: swift-actions/setup-swift@364295d9c23900ce04d4e5cc708387921b4e50f9 # v3
        with:
          swift-version: "6.2"
          skip-verify-signature: true

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v5
        with:
          key: spm-cfpweb-${{ runner.os }}-swift-6.2-${{ hashFiles('CfPWeb/Package.resolved', 'CfPWeb/Package.swift') }}
          restore-keys: spm-cfpweb-${{ runner.os }}-swift-6.2-
          path: CfPWeb/.build

      - name: Build
        run: |
          cd CfPWeb
          swift build
